version: '3.5'
  
services:

  sample-app:
    container_name: sample-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src/:/usr/src/app/src:ro'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
